---
- hosts: webserver
  become: true
  tasks:
  - name: copy file from host to server
    tags: apache2,apache,httpd
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
